theme: jekyll-theme-minimal
title: <div align="center"><img src="images/A.PNG" width="200"/></div>
description: My field? I don't have a field, I'm not a donkey.<br /><br /><a href="https://github.com/jacopotagliabue" target="_blank"><img src="images/github.png" width="23"/></a>&nbsp;&nbsp;<a href="https://www.linkedin.com/in/jacopotagliabue/" target="_blank"><img src="images/linkedin.png" width="23"/></a>&nbsp;&nbsp;<a href="https://scholar.google.com/citations?user=NDX19U0AAAAJ&hl=en" target="_blank"><img src="images/scholar.png" width="23"/></a>
google_analytics: UA-34006119-1
